### ISSUE TITLE
Color camera output

### ISSUE THREAD

**Issue by araujokth** [chutsu/rs4se#4]
Hi Christopher,

I wanted to be able to get images + IMU from the D435i but somehow I was getting a really weird jitter when using the unite_imu_method provided by intel (https://github.com/IntelRealSense/realsense-ros/issues/898) and ended up finding your repo. I have just tried it and the imu timestamps are periodic as expected, which is great and thanks a lot for that! 

One thing I noticed was that you are not outputting the color camera images at the moment (/camera/color/image_raw) and was wondering if you were already implementing this or planning to have this in the near future?

**Comment by chutsu** [comment]
> One thing I noticed was that you are not outputting the color camera images at the moment (/camera/color/image_raw) and was wondering if you were already implementing this or planning to have this in the near future?

Unfortunately, no. Because I originally made this repo just so that I can do SLAM with the Intel D435i. The RGB camera on the Intel D435i in my opinion isn't good enough for SLAM. An ideal camera for SLAM would be a global shutter camera (Stereo IR cameras), rather than a rolling shutter one (RGB camera). 

I personally tried collecting calibration data on the RGB sensor but found significant image blurr despite how I tuned the exposure time & sensitivity. As such if you actually tried to do SLAM on blurry images I am not convinced you'll get good state estimation.

Is there another reason why you need the RGB?

**Comment by araujokth** [comment]
That's a very good point, but its still quite a good challenge to try to get SLAM to work on a rolling shutter camera and overcome those issues I think. But I totally see your point that is just making things harder. I have actually been able to make maplab run with images and IMU data from a Samsung S9 in a pretty stable way, so I was thinking of just having that possibility open when using the D435i. Another reason was to be able to get RGB images so that you can use this sensor for reconstruction with color.

Another question I had was regarding the depth data. Are you planning to output that data as well? The reason would be to be able to run a depth-based SLAM with support from the IMU to get a more robust estimate.

Thanks again!

**Comment by chutsu** [comment]
> its still quite a good challenge to try to get SLAM to work on a rolling shutter camera and overcome those issues I think.

I'll see what I can do. No promises though.

> Another question I had was regarding the depth data. Are you planning to output that data as well?

I should get paid by intel to do this ros driver...

In anycase, I'm not planning on opening up depth data anytime soon (maybe after mid-September - due to paper deadline). From brief conversations with my collegues who used the `realsense-ros` to obtain RGB + Depth data, they told me that the depth data isn't ideal. They experimented with the old Kinetic and found the depth data to be much better in comparison.

**Comment by araujokth** [comment]
No worries, totally understand and thanks again for this great ros driver! Good luck with your paper submission too!

**Comment by chutsu** [comment]
Really late, but if you need all the sensors `rs4se` now has additional support for:

- RGB
- Depth (aligned to RGB camera)

Hope its useful.
